### ISSUE TITLE
Player getting HP back when shot. Might be because of where the juice spawns and it auto heals from its own juice

### ISSUE THREAD

**Issue by jeffcerto** [symbol24/ProjectJuice#111]

**Comment by monstervictor** [comment]
This is fixed with the property of the circle radious. It might take longer for that player to pick up its own juice.
0.3 seems to be fine so far. If there are any undesired effects, let me know

![autohealingback](https://cloud.githubusercontent.com/assets/3688151/10681242/37432470-78f5-11e5-8290-19f8394ce1e6.PNG)

**Comment by BenGoulet** [comment]
Jeff: Make sure this doesn't adversely affect the pick up of Juice on the ground for both the player that lost the juice and the player that picks it up.

**Comment by BenGoulet** [comment]
Looks fixed.
